services:
  frontend:
    image: chaiyah/hyrule-compendium:latest
    container_name: hyrule_frontend
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    build: .
    container_name: hyrule_backend
    restart: always
    environment:
      DB_NAME: ${GLOBAL_DB_NAME}
      DB_HOST: db
      DB_PORT: ${GLOBAL_DB_PORT}
      DB_USER: ${GLOBAL_DB_USER}
      DB_PASSWORD: ${GLOBAL_DB_PASSWORD}
      PORT: ${PORT}
    ports:
      - "3000:3000"
    command: sh -c "node db/seed.js && npm run dev"
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${GLOBAL_DB_NAME}
      POSTGRES_PASSWORD: ${GLOBAL_DB_PASSWORD}
      POSTGRES_USER: ${GLOBAL_DB_USER}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
